{"$schema": "https://schemas.exasol.com/error_code_report-1.0.0.json", "projectName": "exasol-error-reporting", "projectVersion": "1.0.0", "errorCodes": [{"identifier": "E-ERP-1", "message": "Invalid error code {{code}}.", "messagePlaceholders": [{"placeholder": "code", "description": "Error code which was causing the error."}], "mitigations": ["Ensure you follow the standard error code format."], "sourceFile": "_internal_errors.py"}, {"identifier": "E-ERP-2", "message": "Unknown error/exception occurred.", "messagePlaceholders": [{"placeholder": "traceback", "description": "Exception traceback which lead to the generation of this error."}], "description": "An unexpected error occurred during the creation of the error", "mitigations": ["A good starting point would be to investigate the cause of the attached exception.\n\nTrackback:\n    {{traceback}}"], "sourceFile": "_internal_errors.py"}, {"identifier": "E-ERP-3", "message": "Invalid error code definition: {{error_element}} only can contain constant values, but is of type: {{defined_type}}. In file {{file}} line {{line}}", "messagePlaceholders": [{"error_element": "The element within the error definition which caused the error.", "defined_type": "The actual Python type of the error definition.", "file": "The file in which the error occurred.", "line": "The line where the error occurred."}], "description": "An unexpected error occurred during the creation of the error catalog, when parsing the project for EXA error codes.", "mitigations": ["Check the definition of ExaError. Possible errors: \n1. Usage of none-constant expression in error code, message\n2. Mitigations are not a list, but another container\n3. Invalid definition of parameters."], "sourceFile": "_internal_errors.py"}, {"identifier": "E-ERP-4", "message": "Internal error during creation of the error catalog. Details to append on Bug ticket: {{traceback}}", "messagePlaceholders": [{"traceback": "Traceback which was collected when creating this error."}], "description": "This error signals a programming error in the exasol.error library.", "mitigations": ["Open a bug ticket at \nhttps://github.com/exasol/error-reporting-python/issues/new?template=bug.md"], "sourceFile": "_internal_errors.py"}]}